---
- name: create blocklist directory - osx
  when: hostvars[inventory_hostname]['ansible_system'] == "Darwin"
  file: path="~/Library/Application Support/Transmission/blocklists" state=directory

- name: create blocklist directory - linux
  when: hostvars[inventory_hostname]['ansible_os_family'] == "Linux"
  file: path="~/.config/transmission/blocklists/" state=directory

- name: create tmp directory
  file: path=/tmp/blocklist state=directory

- name: get blocklists
  get_url: url="http://list.iblocklist.com/?list={{ item }}&fileformat=p2p&archiveformat=gz" dest="/tmp/blocklist/{{ item }}.gz"
  with_items:
    - bt_level2
    - bt_level3
    - bt_edu
    - bt_ads
    - bt_spyware
    - bt_proxy
    - bt_templist
    - bt_microsoft
    - bt_spider
    - bt_hijacked
    - bt_dshield
    - ficutxiwawokxlcyoeye
    - ghlzqtqxnzctvvajwwag
    - ijfqtofzixtwayqovmxn
    - ecqbsykllnadihkdirsh
    - jcjfaxgyyshvdbceroxf
    - lljggjrpmefcwqknpalp

- name: decompress lists
  command: gzip -d {{ item }}
  with_fileglob:
    - /tmp/blocklist/*.gz

- name: copy blocklist - osx
  when: hostvars[inventory_hostname]['ansible_os_family'] == "Darwin"
  copy: src={{ item }} dest="~/Library/Application Support/Transmission/blocklists/" force=yes
  with_fileglob:
    - /tmp/blocklist/*

- name: copy blocklist - linux
  when: hostvars[inventory_hostname]['ansible_os_family'] == "Linux"
  copy: src={{ item }} dest="~/.config/transmission/blocklists/" force=yes
  with_fileglob:
    - /tmp/blocklist/*

- name: remove tmp directory
  file: state=absent path="/tmp/blocklist/"
